chore(dependencies): bump System.Text.Json to 8.0.4
eclipse-tractusx/ssi-authority-schema-registry pull request #46
Opened 2024-07-26 14:56 UTC by ntruchsess

## Description

dependency to Microsoft.EntityFrameworkCore was changed to Microsoft.EntityFrameworkCore.Design 8.0.7

## Why

System.Text.Json 8.0.0 has a vulnerability that must be fixed. It is references as an implicit dependency. Referencing Microsoft.EntityFrameworkCore.Design 8.0.7 instead of Microsoft.EntityFrameworkCore implicitly upgrades System.Json.Text to 8.0.4 which solves the security-issue.

## Issue

https://github.com/eclipse-tractusx/portal/issues/369

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/ssi-authority-schema-registry/blob/main/docs/technical-documentation/dev-process/How%20to%20contribute.md)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally
- [X] I have checked that new and existing tests pass locally with my changes

2024-07-26 15:17 UTC, evegufy approved these changes

2024-07-29 06:31 UTC, Phil91 requested changes
We should wait until PR https://github.com/eclipse-tractusx/portal-backend/pull/875 is merged and the framework nuget packages are updated. We than can directly update the nuget packages for this project as well.

2024-07-29 13:15 UTC, Phil91 approved these changes

2024-07-29 13:15 UTC, Phil91 requested changes
please update the dependency file

2024-07-29 13:26 UTC, Phil91 approved these changes

2024-07-29 14:09 UTC, merged