docs(trg1): align docs directory structure
eclipse-tractusx/ssi-authority-schema-registry pull request #71
Opened 2024-10-01 13:56 UTC by typecastcloud

## Description

- move existing documents to folder structure in trg 1. eclipse-tractusx/sig-release#805
- create README.md with references
- rename existing files with clear relation to arc42 standard 

## Why

Follow TRG 1

## Issue

Closes: eclipse-tractusx/ssi-authority-schema-registry#58
Refs: eclipse-tractusx/sig-release#805

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/ssi-authority-schema-registry/blob/main/docs/technical-documentation/dev-process/How%20to%20contribute.md)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have added copyright and license headers, footers (for .md files) or files (for images)

2024-10-15 14:40 UTC, evegufy requested changes
Looks really good so far, just some comments

2024-10-15 14:40 UTC, evegufy commented on docs/api/Org.Eclipse.TractusX.SsiAuthoritySchemaRegistry.Service.postman_collection.json
quite recently there was an api directory introduced: https://github.com/Cofinity-X/entry-ssi-authority-schema-registry/blob/edc06c1c739bdbc679821a8acea79791b2f167a0/docs/api/asr-service.yaml
As part of https://github.com/eclipse-tractusx/ssi-authority-schema-registry/pull/66
So, the asr-service.yaml file should be in this directory.

@Phil91 where should be put the postman collection? Maybe api/requests? Are we still maintaining the collection in addition to the api spec?

2024-10-15 14:40 UTC, evegufy commented on docs/README.md
I think the docs/README.md is intented to provide a short overview about the the available documentation and shouldn't be be limited to presenting the arc42 structure, but great that you added a glossary, maybe you want to add it as a separate file under /architecture?

2024-10-17 09:31 UTC, typecastcloud commented on docs/README.md
I didn't want to repeat anything already written in the linked document. Do you think the README should contain a list of what the document already contains or what it is supposed to contain?

2024-10-17 09:32 UTC, typecastcloud commented on docs/api/Org.Eclipse.TractusX.SsiAuthoritySchemaRegistry.Service.postman_collection.json
I moved the postman collection into docs/api/postman folder I created to make it more clear.

2024-10-23 09:45 UTC, typecastcloud commented on docs/README.md
Hi @evegufy, thank you for the feedback and link to the example.

I reworked the structure of all documents I could find and renamed them in arc42 format.

There are some documents missing for full compliance with arc42.

2024-10-23 11:20 UTC, evegufy requested changes
Looks very good, just some small comments still

2024-10-23 11:20 UTC, evegufy commented on docs/README.md
> +| [Interface Documentation](api/Interface_Doc.md)                  | Information about the interfaces.                               |
```suggestion
| [API Documentation](api/API_Doc.md)                  | Information about the endpoints.                               |
```

2024-10-23 11:20 UTC, evegufy commented on docs/api/Interface_Doc.md
> +# Interface Documentation
```suggestion
# API Documentation
```

2024-10-23 11:20 UTC, evegufy commented on docs/api/Interface_Doc.md
> +documentations.
```suggestion
This document provides information on the endpoints.
```

2024-10-23 11:20 UTC, evegufy commented on docs/api/Interface_Doc.md
> +The [Building Block View](../architecture/05_building_block_view.md) provides an overview.
```suggestion
```

2024-10-23 11:32 UTC, typecastcloud commented
> Looks very good, just some small comments still

Good feedback @evegufy. Less confusing. Resolved.

2024-10-23 12:40 UTC, evegufy approved these changes
thank you! could you please still change the PR title `docs(trg1): align docs directory structure`
I find the issue number sig805 very useful in the PR description and branch name, but not so much in the title of the PR.

@Phil91 would you like to review as well?

2024-10-23 12:54 UTC, typecastcloud commented
> thank you! could you please still change the PR title `docs(trg1): align docs directory structure` I find the issue number sig805 very useful in the PR description and branch name, but not so much in the title of the PR.
> 
> @Phil91 would you like to review as well?

Title updated and sig release issue linked/referenced in description.

2024-10-23 15:09 UTC, Phil91 approved these changes
looks really really good!

2024-10-24 05:02 UTC, merged